services:
  postgres:
    image: 'postgres:16.3-alpine'
    environment:
      - 'POSTGRES_DB=speedshield'
      - 'POSTGRES_PASSWORD=speedshield'
      - 'POSTGRES_USER=speedshield'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379:6379'
